### ISSUE TITLE
Support Julia 0.5

### ISSUE THREAD

**Issue by daanhb** [daanhb/FrameFuns.jl#2]
Currently, FrameFuns and BasisFunctions are not compatible with Julia 0.5, and importing them fails.

**Comment by kuanxu** [comment]
It'll be thrilling if Gallium and ASTinterpreter are supported as well.

**Comment by daanhb** [comment]
The main thing stopping this was JuliaLang/julia#14919, but there is an easy workaround (just not an elegant one). Tests are passing in 0.5 with the julia-0.5 branch of FrameFuns and BasisFunctions. There are still some warnings and the output of the test suite needs to be fixed, but the functionality seems to be okay. Once those are fixed, we'll merge to master. Or to a development branch, which we really should start thinking about.

Is there anything else to do to support Gallium and ASTinterpreter, besides supporting julia 0.5? I have not used them yet.

**Comment by kuanxu** [comment]
@daanhb I wasn't aware of that issue. But as long as both FrameFuns and BasisFunctions are now compatible with Julia-0.5, we're OK and can take the botch for a while until Julia people get the issue fully resolved, if ever possible.

Yes, it's the best practice that we have a development branch for up-to-date development, on which nightly build may be introduced in the medium future. And the master branch can be saved for stable version/release, once you guys decide to register these two projects on METADATA.

Finally, I don't think you need anything else to support Gallium and ASTinterpreter, as long as the code works with Julia-0.5. But I only used Gallium and ASTinterpreter for some short code examples, not anything as big as BasisFunctions and FrameFuns. I basically followed this clip when learning the very basic of Gallium: https://www.youtube.com/watch?v=Kv6TO_gm2yw. But many things may have been changed in the past 9 months. If I understand correctly, the Gallium documentation is still too sketchy to give much detail.

**Comment by daanhb** [comment]
I have pushed the changes for 0.5 to master. The code should still work in 0.4 (using the Compat package), but the tests have been adapted and now only work in 0.5. The tests seem to be passing. PyPlot generates a lot of warnings currently in 0.5, but that will probably go away once 0.5 is released.

I hope this update does not break things for you @kuanxu. Next changes we will do in a development branch first!

**Comment by kuanxu** [comment]
@daanhb Bravo! The migration to 0.5 seems seamless. It doesn't affect even a single line of my work. Hopefully, when 0.5 is formally released, we'll see great compatibility for the new debuggers. Many thanks!

**Comment by daanhb** [comment]
Ok, thanks for confirming. Ready to close then :-)
